# Generated by Django 5.2.8 on 2025-11-25 20:51

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "content_md",
                    models.TextField(blank=True, verbose_name="المحتوى (Markdown)"),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True, editable=False, verbose_name="المحتوى (HTML)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="مشاركة عامة"),
                ),
                (
                    "public_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="الرابط العام",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="عدد المشاهدات")),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="مفضلة"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالك",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="الوسوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة",
                "verbose_name_plural": "الملاحظات",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_md", models.TextField(verbose_name="المحتوى (Markdown)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="notes.note",
                        verbose_name="الملاحظة",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخة ملاحظة",
                "verbose_name_plural": "نسخ الملاحظات",
                "ordering": ["-created_at"],
            },
        ),
    ]
